### ISSUE TITLE
Invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by njacob1001** [wubostc/virtualized-table-for-antd#45]
I've tried to use useVT like 

```javascript
import React, {useRef, useEffect} from 'react'
import {useVT} from 'virtualizedtableforantd'

const MyTable = () => {
    const ctx = useRef({})
    const [VT, setComponents, VTScroll] = useVT({onScroll: {}})

    useEffect(()=> {
        return () => {
            const loc = VTScroll(id.current)
           ctx.current.top = loc.top
        }
    },[])
    
    return <Table components={VT} {...rest} />
}
```

**Comment by wubostc** [comment]
I just tested it again and it works fine.

**Comment by njacob1001** [comment]
> I just tested it again and it works fine.

Could you create an example in code sandbox please? I don't understand why in my project it doesn't work

**Comment by njacob1001** [comment]
exmaple in https://github.com/wubostc/virtualized-table-for-antd/blob/master/test/CustomRows%20Hooks.jsx

Thanks!

**Comment by wubostc** [comment]
> 
> 
> example in https://github.com/wubostc/virtualized-table-for-antd/blob/master/test/CustomRows%20Hooks.jsx
> 
> Thanks!

https://codesandbox.io/s/intelligent-knuth-1l5fm?fontsize=14&hidenavigation=1&theme=dark

**Comment by hemanthvrm** [comment]
@wubostc 

hey thanks for wonderful library and continuous support. i do have a question, hope you find some time to answer..

**0.7.8 and older**
for old version which supports antdesign 3, react ^16 and react-dom^16 is mentioned in dependencies instead peerDependencies..
so if existing project uses  react version anything less than 16.14.0, there will be two copies of react and react dom..
since virtualized-table-for-antd will download one more 16.14.0 version other than the existing one..

which results in following error i believe..

and i don't see 0.7.8 branch as well, to fix it myself.. are you guys not supporting older version anymore?

**Comment by wubostc** [comment]
@hemanthvrm hello , the 0.7.8 is [here](https://github.com/wubostc/virtualized-table-for-antd/tree/v3.x)
you can push your own PR to me...

**Comment by hemanthvrm** [comment]
@wubostc  thanks ..sure will do that soon...

Meanwhile for anyone who is looking for a temp fix..
if you guys are using yarn then you can add below resolutions to your package.json (provide your exact react and dom version)

 "resolutions": {
    "react": " ",
    "react-dom": " "
  },

**Comment by wubostc** [comment]
@hemanthvrm   a new commit f783f50 had been pushed...
Is there anything else you want to add?

**Comment by hemanthvrm** [comment]
@wubostc ..
that will be all...
thank you so much
